apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: chartofapps
  name: perf-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: perf-vcluster
      namespace: perf*
      server: https://perf-vcluster.jpmc.opsmx.net:443
  sourceRepos:
    - '*'
  syncWindows:
    - applications:
        - '*'
      duration: 1h
      kind: allow
      manualSync: true
      schedule: '* 11 * * *'
      timeZone: UTC
