apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: chartofapps
  name: qa-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: qa-cluster
      namespace: qa
      server: https://qa-cluster.jpmc.opsmx.net:443
    - name: qa-vcluster
      namespace: qa*
      server: https://qa-vcluster.jpmc.opsmx.net:443
  sourceRepos:
    - '*'
  syncWindows:
    - applications:
        - '*'
      duration: 1h
      kind: allow
      manualSync: true
      schedule: '* 11 * * *'
      timeZone: UTC
