apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.environment }}-{{ .Values.appname }}
  namespace: argocd
  annotations: 
    {{- range $key, $value := .Values.metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels: 
     org: {{ .Values.org }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.cluster }}
  project: {{ .Values.environment }}-project
  source:
    path: {{ .Values.appname }}{{ .Values.customname }}/{{ .Values.environment }}
    repoURL: {{ .Values.gitrepo }}
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy: 
  {{- if .Values.spec.syncPolicy.automated }}
    automated:
      {{- range $key, $value := .Values.spec.syncPolicy.automated }}
      {{ $key }}: {{ $value }}
      {{- end }}
  {{- end }}
    syncOptions:
      {{- range .Values.spec.syncPolicy.syncOptions }}
      - {{ . }}
      {{- end }}


