---
# Source: apps-helm-chart/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-yuga2
  namespace: argocd
  labels: 
     org: opsmx
spec:
  destination:
    namespace: qa-yuga2
    name: in-cluster
  project: qa-project
  source:
    path: yuga2-mainchart/qa
    repoURL: https://github.com/gopaljayanthi/wisetech-k8s-repo
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      #- qa-values.yaml
      #- yuga2/yuga2-values.yaml
      #- yuga2/qa-yuga2-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true
