environment: dev
namespace: dev-wtdemo
cluster: dev-vcluster
metadata:
  annotations:
    argocd-image-updater.argoproj.io/micro-ui.allow-tags: regexp:^mybranch
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^mybranch
    argocd-image-updater.argoproj.io/external.allow-tags: regexp:^mybranch
    argocd-image-updater.argoproj.io/es-sync.allow-tags: regexp:^mybranch
    notifications.argoproj.io/subscribe.on-deployed.github: maonchart-qa-on-deployed
