---
# Source: apps-helm-chart/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mbe
  namespace: argocd
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: dev-project
  source:
    path: mbe-mainchart/dev
    repoURL: https://github.com/gopaljayanthi/wisetech-k8s-repo
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - dev-values.yaml
      - mbe/mbe-values.yaml
      - mbe/dev-mbe-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
