---
# Source: apps-helm-chart/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-mbe
  namespace: argocd
spec:
  destination:
    namespace: qa
    name: in-cluster
  project: qa-project
  source:
    path: mbe-mainchart/qa
    repoURL: https://github.com/gopaljayanthi/wisetech-k8s-repo
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - qa-values.yaml
      - mbe/mbe-values.yaml
      - mbe/qa-mbe-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
