metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'argocd-image-updater.argoproj.io/image-list: app=docker.io/gopalvithaljayanthi/nginx,es-sync=docker.io/gopalvithaljayanthi/nginx,external=docker.io/gopalvithaljayanthi/nginx,micro-ui=docker.io/gopalvithaljayanthi/nginx'
    argocd-image-updater.argoproj.io/app.helm.image-name: docker.io/gopalvithaljayanthi/nginx
    argocd-image-updater.argoproj.io/app.ignore-tags: somethingorother
    argocd-image-updater.argoproj.io/app.helm.image-tag: app.image.tag
    argocd-image-updater.argoproj.io/es-sync.helm.image-name: docker.io/gopalvithaljayanthi/nginx
    argocd-image-updater.argoproj.io/es-sync.ignore-tags: somethingorother
    argocd-image-updater.argoproj.io/es-sync.helm.image-tag: es-sync.image.tag
    argocd-image-updater.argoproj.io/external.update-strategy: latest
    argocd-image-updater.argoproj.io/external.helm.image-name: docker.io/gopalvithaljayanthi/nginx
    argocd-image-updater.argoproj.io/external.ignore-tags: somethingorother
    argocd-image-updater.argoproj.io/external.helm.image-tag: external.image.tag
    argocd-image-updater.argoproj.io/micro-ui.update-strategy: latest
    argocd-image-updater.argoproj.io/micro-ui.helm.image-name: docker.io/gopalvithaljayanthi/nginx
    argocd-image-updater.argoproj.io/micro-ui.ignore-tags: somethingorother
    argocd-image-updater.argoproj.io/micro-ui.helm.image-tag: microui.image.tag

