apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-mbe
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  sources:
  - path: apps-helm-chart/
    repoURL: https://github.com/gopaljayanthi/wisetech-argocd-apps
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
      - prod-values.yaml
      - mbe/mbe-values.yaml
      - mbe/prod-mbe-values.yaml
  - path: apps-helm-chart/
    repoURL: https://github.com/gopaljayanthi/wisetech-argocd-apps
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
      - qa-values.yaml
      - mbe/mbe-values.yaml
      - mbe/qa-mbe-values.yaml
  syncPolicy:
    automated:
      prune: true
