---
# Source: mbe/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-benda
  namespace: argocd
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: dev-project
  source:
    path: benda-mainchart/dev
    repoURL: https://github.com/gopaljayanthi/wisetech-k8s-repo
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
