apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selfdeployingapp
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: selfdeployingapp
   # repoURL: https://github.com/gopaljayanthi/wisetech-argocd-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true